# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuiodo < Formula
  desc "A modern terminal task manager with extensive customization"
  homepage "https://github.com/spmfte/tuiodo"
  version "1.1.4"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spmfte/tuiodo/archive/refs/tags/v1.1.4.tar.gz"
      sha256 "f9f5da26dfb126027e691cd211e8e359fb94872516a8588cb0fe559452c4fe95"

      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spmfte/tuiodo/archive/refs/tags/v1.1.4.tar.gz"
      sha256 "666aa7be7c387cde6db280f03779461ac346b640322c4fc545f7204fb9a89963"

      def install
        bin.install "tuiodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/archive/refs/tags/v1.1.4.tar.gz"
      sha256 "abc2d921517bdfb65143b4f491078bc805693e08f1ed9f7964650f71b0f833dc"
      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/archive/refs/tags/v1.1.4.tar.gz"
      sha256 "66d8440ad722d6433832870012171aa4fa21baf752825fcf8d43f35106ebe8bc"
      def install
        bin.install "tuiodo"
      end
    end
  end

  test do
    system "#{bin}/tuiodo", "--version"
  end
end
