# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuiodo < Formula
  desc "A modern terminal task manager with extensive customization"
  homepage "https://github.com/spmfte/tuiodo"
  version "1.1.4"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Darwin-x86_64.tar.gz"
      sha256 "7b7930c32a9a688a21aa7f1ff4e3fa134824f6a5b11e89278696d8dcf3c5c19f"

      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Darwin-arm64.tar.gz"
      sha256 "1d793c62433b06d3a360312c371d5ae6f57b96634f692510e1e2ffca0d88ea71"

      def install
        bin.install "tuiodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Linux-x86_64.tar.gz"
      sha256 "6d3dc9cbd3d97063adc36a6d880c7300c9dc40eadab22e8a8e502b29bd54e257"
      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Linux-arm64.tar.gz"
      sha256 "d595c490151d0dc95d59fe7b0078925194a0390226adf2e336cf7c576c0483ff"
      def install
        bin.install "tuiodo"
      end
    end
  end

  test do
    system "#{bin}/tuiodo", "--version"
  end
end
