# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tuiodo < Formula
  desc "A modern terminal task manager with extensive customization"
  homepage "https://github.com/spmfte/tuiodo"
  version "1.1.4"
  license "MIT"

  depends_on "go"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Darwin-x86_64.tar.gz"
      sha256 "3718d1980d2dae47f940b15bd761bd97afec887d82be10f1d798e24f7cc12f58"

      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Darwin-arm64.tar.gz"
      sha256 "192e7a555ad48aeb9449f261825d319056b880a4e054ecb0695e7081a0c89bf3"

      def install
        bin.install "tuiodo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Linux-x86_64.tar.gz"
      sha256 "2f0bc60e1e76e53fbfc1d39ea51dbed61af04d4ed22c7039fad8f762c36da08f"
      def install
        bin.install "tuiodo"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/spmfte/tuiodo/releases/download/v1.1.4/tuiodo-Linux-arm64.tar.gz"
      sha256 "b4bd2e3dab7884e9a9d239aff6f9fbc177caf1b8dd28ecb1e9e86b1e150c9b37"
      def install
        bin.install "tuiodo"
      end
    end
  end

  test do
    system "#{bin}/tuiodo", "--version"
  end
end
